<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use App\Lga;
use Illuminate\Support\Str;

class LgaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
    */
    public function run()
    {
        $abia = [
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Aba North"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Aba South"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Arochukwu"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Bende"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Ikwuano"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Isiala Ngwa North"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Isiala Ngwa South"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Isuikwuato"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Obi Ngwa"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Ohafia"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Osisioma"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Ugwunagbo"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Ukwa East"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Ukwa West"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Umuahia North"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "muahia South"],
            ["state_id" => 1,  "slug"=>Str::uuid(), "name" => "Umu Nneochi"]
        ];
        $adamawa = [
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Demsa"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Fufure"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Ganye"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Gayuk"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Gombi"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Grie"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" =>  "Hong"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Jada"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Larmurde"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Madagali"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Maiha"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Mayo Belwa"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Michika"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Mubi North"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Mubi South"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Numan"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Shelleng"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Song"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Toungo"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" => "Yola North"],
            ["state_id" => 2,  "slug"=>Str::uuid(), "name" =>  "Yola South"]
        ];
        $akwaIbom = [
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Abak"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Eastern Obolo"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Eket"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Esit Eket"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Essien Udim"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Etim Ekpo"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Etinan"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Ibeno"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Ibesikpo Asutan"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Ibiono-Ibom"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Ika"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Ikono"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Ikot Abasi"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Ikot Ekpene"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Ini"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Itu"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Mbo"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Mkpat-Enin"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Nsit-Atai"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Nsit-Ibom"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Nsit-Ubium"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Obot Akara"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Okobo"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Onna"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Oron"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Oruk Anam"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Udung-Uko"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Ukanafun"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Uruan"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Urue-Offong Oruko"],
            ["state_id" => 3,  "slug"=>Str::uuid(), "name" => "Uyo"]
        ];
        $anambra = [
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Aguata"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Anambra East"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Anambra West"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Anaocha"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Awka North"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Awka South"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Ayamelum"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Dunukofia"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Ekwusigo"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Idemili North"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Idemili South"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Ihiala"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Njikoka"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Nnewi North"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Nnewi South"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Ogbaru"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Onitsha North"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Onitsha South"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Orumba North"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Orumba South"],
            ["state_id" => 4,  "slug"=>Str::uuid(), "name" => "Oyi"]
        ];
        $bauchi = [
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Alkaleri"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Bauchi"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Bogoro"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Damban"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Darazo"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Dass"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Gamawa"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Ganjuwa"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Giade"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Itas-Gadau"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Jama are"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Katagum"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Kirfi"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Misau"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Ningi"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Shira"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Tafawa Balewa"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => " Toro"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => " Warji"],
            ["state_id" => 5,  "slug"=>Str::uuid(), "name" => "Zaki"]
        ];
        $bayelsa = [
            ["state_id" => 6,  "slug"=>Str::uuid(), "name" => "Brass"],
            ["state_id" => 6,  "slug"=>Str::uuid(), "name" => "Ekeremor"],
            ["state_id" => 6,  "slug"=>Str::uuid(), "name" => "Kolokuma Opokuma"],
            ["state_id" => 6,  "slug"=>Str::uuid(), "name" => "Nembe"],
            ["state_id" => 6,  "slug"=>Str::uuid(), "name" => "Ogbia"],
            ["state_id" => 6,  "slug"=>Str::uuid(), "name" => "Sagbama"],
            ["state_id" => 6,  "slug"=>Str::uuid(), "name" => "Southern Ijaw"],
            ["state_id" => 6,  "slug"=>Str::uuid(), "name" => "Yenagoa"]
        ];
        $benue = [
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Agatu"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Apa"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Ado"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Buruku"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Gboko"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Guma"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" =>  "Gwer East"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Gwer West"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Katsina-Ala"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Konshisha"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Kwande"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Logo"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Makurdi"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Obi"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Ogbadibo"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Ohimini"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Oju"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Okpokwu"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Oturkpo"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Tarka"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Ukum"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Ushongo"],
            ["state_id" => 7,  "slug"=>Str::uuid(), "name" => "Vandeikya"]
        ];
        $borno = [
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Abadam"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Askira-Uba"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Bama"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Bayo"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Biu"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Chibok"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Damboa"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Dikwa"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Gubio"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Guzamala"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Gwoza"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Hawul"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Jere"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Kaga"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Kala-Balge"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Konduga"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Kukawa"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Kwaya Kusar"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Mafa"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Magumeri"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Maiduguri"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Marte"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Mobbar"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Monguno"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Ngala"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Nganzai"],
            ["state_id" => 8,  "slug"=>Str::uuid(), "name" => "Shani"]
        ];
        $crossRiver = [
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Abi"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Akamkpa"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Akpabuyo"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Bakassi"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Bekwarra"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Biase"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Boki"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Calabar Municipal"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Calabar South"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Etung"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Ikom"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Obanliku"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Obubra"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Obudu"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Odukpani"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Ogoja"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Yakuur"],
            ["state_id" => 9,  "slug"=>Str::uuid(), "name" => "Yala"]
        ];
        $delta = [
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Aniocha North"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Aniocha South"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Bomadi"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Burutu",],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Ethiope East"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Ethiope West"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Ika North East"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Ika South"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Isoko North"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Isoko South"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Ndokwa East"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Ndokwa West"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Okpe"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Oshimili North"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Oshimili South"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" =>  "Patani"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Sapele"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Udu"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Ughelli North"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Ughelli South"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Ukwuani"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Uvwie"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Warri North"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Warri South"],
            ["state_id" => 10, "slug"=>Str::uuid(), "name" => "Warri South West"]
        ];

        $ebonyi = [
            ["state_id" => 11, "slug"=>Str::uuid(), "name" => "Abakaliki"],
            ["state_id" => 11, "slug"=>Str::uuid(), "name" => "Afikpo North"],
            ["state_id" => 11, "slug"=>Str::uuid(), "name" => "Afikpo South"],
            ["state_id" => 11, "slug"=>Str::uuid(), "name" => "Ebonyi"],
            ["state_id" => 11, "slug"=>Str::uuid(), "name" => "Ezza North"],
            ["state_id" => 11, "slug"=>Str::uuid(), "name" => "Ezza South"],
            ["state_id" => 11, "slug"=>Str::uuid(), "name" => "Ikwo"],
            ["state_id" => 11, "slug"=>Str::uuid(), "name" => "Ishielu"],
            ["state_id" => 11, "slug"=>Str::uuid(), "name" =>  "Ivo"],
            ["state_id" => 11, "slug"=>Str::uuid(), "name" => "Izzi"],
            ["state_id" => 11, "slug"=>Str::uuid(), "name" => "Ohaozara"],
            ["state_id" => 11, "slug"=>Str::uuid(), "name" => "Ohaukwu"],
            ["state_id" => 11, "slug"=>Str::uuid(), "name" => "Onicha"]
        ];
        $edo = [
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Akoko-Edo"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Egor"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Esan Central"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Esan North-East"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Esan South-East"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Esan West"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Etsako Central"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Etsako East"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Etsako West"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Igueben"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Ikpoba Okha"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Orhionmwon"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Oredo"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Ovia North-East"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Ovia South-West"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Owan East"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Owan West"],
            ["state_id" => 12, "slug"=>Str::uuid(), "name" => "Uhunmwonde"]
        ];
        $ekiti = [
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Ado Ekiti"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Efon"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Ekiti East"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Ekiti South-West"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Ekiti West"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Emure"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Gbonyin"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Ido Osi"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Ijero"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Ikere"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Ikole"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Ilejemeje"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Irepodun-Ifelodun"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Ise-Orun"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Moba"],
            ["state_id" => 13, "slug"=>Str::uuid(), "name" => "Oye"]
        ];
        $rivers = [
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Port Harcourt"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Obio-Akpor"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Okrika"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Ogu–Bolo"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Eleme"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Tai"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Gokana"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Khana"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Oyigbo"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Opobo–Nkoro"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Andoni"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Bonny"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Degema"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Asari-Toru"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Akuku-Toru"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Abua–Odual"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Ahoada West"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Ahoada East"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Ogba–Egbema–Ndoni"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Emohua"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Ikwerre"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Etche"],
            ["state_id" => 14, "slug"=>Str::uuid(), "name" => "Omuma"]
        ];
        $enugu = [
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Aninri"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Awgu"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Enugu East"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Enugu North"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Enugu South"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Ezeagu"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Igbo Etiti"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Igbo Eze North"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Igbo Eze South"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Isi Uzo"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Nkanu East"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Nkanu West"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Nsukka"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Oji River"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Udenu"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Udi"],
            ["state_id" => 15, "slug"=>Str::uuid(), "name" => "Uzo Uwani"]
        ];

        $abuja = [
            ["state_id" => 16, "slug"=>Str::uuid(), "name" => "Abaji"],
            ["state_id" => 16, "slug"=>Str::uuid(), "name" => "Bwari"],
            ["state_id" => 16, "slug"=>Str::uuid(), "name" => "Gwagwalada"],
            ["state_id" => 16, "slug"=>Str::uuid(), "name" => "Kuje"],
            ["state_id" => 16, "slug"=>Str::uuid(), "name" =>  "Kwali"],
            ["state_id" => 16, "slug"=>Str::uuid(), "name" => "Municipal Area Council"]
        ];

        $gombe = [
            ["state_id" => 17, "slug"=>Str::uuid(), "name" => "Akko"],
            ["state_id" => 17, "slug"=>Str::uuid(), "name" => "Balanga"],
            ["state_id" => 17, "slug"=>Str::uuid(), "name" => "Billiri"],
            ["state_id" => 17, "slug"=>Str::uuid(), "name" => "Dukku"],
            ["state_id" => 17, "slug"=>Str::uuid(), "name" => "Funakaye"],
            ["state_id" => 17, "slug"=>Str::uuid(), "name" => "Gombe"],
            ["state_id" => 17, "slug"=>Str::uuid(), "name" => "Kaltungo"],
            ["state_id" => 17, "slug"=>Str::uuid(), "name" => "Kwami"],
            ["state_id" => 17, "slug"=>Str::uuid(), "name" => "Nafada"],
            ["state_id" => 17, "slug"=>Str::uuid(), "name" => "Shongom"],
            ["state_id" => 17, "slug"=>Str::uuid(), "name" => "Yamaltu-Deba"]
        ];

        $imo = [
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Aboh Mbaise"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Ahiazu Mbaise"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Ehime Mbano"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Ezinihitte"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Ideato North"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Ideato South"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Ihitte-Uboma"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Ikeduru"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Isiala Mbano"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Isu"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Mbaitoli"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Ngor Okpala"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Njaba"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" =>  "Nkwerre"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Nwangele"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Obowo"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" =>  "Oguta"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" =>  "Ohaji-Egbema"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" =>  "Okigwe"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Orlu"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Orsu"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Oru East"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Oru West"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Owerri Municipal"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Owerri North"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Owerri West"],
            ["state_id" => 18, "slug"=>Str::uuid(), "name" => "Unuimo"]
        ];

        $jigawa =  [
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Auyo"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Babura"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Biriniwa"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Birnin Kudu"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Buji"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Dutse"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Gagarawa"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Garki"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Gumel"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Guri"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Gwaram"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Gwiwa"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Hadejia"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Jahun"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Kafin Hausa"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Kazaure"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Kiri Kasama"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Kiyawa"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Kaugama"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Maigatari"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Malam Madori"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Miga"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Ringim"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Roni"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Sule Tankarkar"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Taura"],
            ["state_id" => 19, "slug"=>Str::uuid(), "name" => "Yankwashi"]
        ];
        $kaduna = [
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Birnin Gwari"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Chikun"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Giwa"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Igabi"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Ikara"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Jaba"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Jema a"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" =>  "Kachia"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Kaduna North"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Kaduna South"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Kagarko"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Kajuru"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Kaura"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Kauru"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Kubau"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Kudan"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Lere"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" =>  "Makarfi"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Sabon Gari"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Sanga"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Soba"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Zangon Kataf"],
            ["state_id" => 20, "slug"=>Str::uuid(), "name" => "Zaria"]
        ];

        $kano = [
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Ajingi"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Albasu"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Bagwai"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Bebeji"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Bichi"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Bunkure"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Dala"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Dambatta"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Dawakin Kudu"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Dawakin Tofa"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Doguwa"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Fagge"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Gabasawa"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Garko"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Garun Mallam"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Gaya"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Gezawa"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Gwale"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Gwarzo"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Kabo"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Kano Municipal"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Karaye"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Kibiya"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Kiru"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Kumbotso"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Kunchi"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Kura"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Madobi"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Makoda"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Minjibir"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Nasarawa"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Rano"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" =>  "Rimin Gado"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" =>  "Rogo"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Shanono"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Sumaila"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Takai"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Tarauni"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Tofa"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Tsanyawa"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" =>  "Tudun Wada"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Ungogo"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Warawa"],
            ["state_id" => 21, "slug"=>Str::uuid(), "name" => "Wudil"]
        ];

        $katsina = [
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Bakori"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Batagarawa"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Batsari"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Baure"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Bindawa"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" =>  "Charanchi"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Dandume"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Danja"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" =>  "Dan Musa"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Daura"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" =>  "Dutsi"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Dutsin Ma"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Faskari"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Funtua"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" =>  "Ingawa"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" =>  "Jibia"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Kafur"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Kaita"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Kankara"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" =>  "Kankia"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Katsina"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Kurfi"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Kusada"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Mai Adua"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Malumfashi"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Mani"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Mashi"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" =>  "Matazu"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Musawa"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Rimi"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Sabuwa"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Safana"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Sandamu"],
            ["state_id" => 22, "slug"=>Str::uuid(), "name" => "Zango"]
        ];

        $kebbi = [
            ["state_id" => 23, "slug"=>Str::uuid(), "name" =>  "Aleiro"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Arewa Dandi"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Argungu"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Augie"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" =>  "Bagudo"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Birnin Kebbi"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Bunza"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Dandi"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Fakai"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Gwandu"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Jega"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Kalgo"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Koko Besse"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Maiyama"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Ngaski"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Sakaba"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Shanga"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Suru"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Wasagu Danko"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Yauri"],
            ["state_id" => 23, "slug"=>Str::uuid(), "name" => "Zuru"]
        ];

        $kogi = [
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Adavi"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Ajaokuta"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Ankpa"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Bassa"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Dekina"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Ibaji"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Idah"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Igalamela Odolu"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Ijumu"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Kabba Bunu"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Kogi"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Lokoja"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Mopa Muro"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Ofu"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Ogori Magongo"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Okehi"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Okene"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Olamaboro"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Omala"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Yagba East"],
            ["state_id" => 24, "slug"=>Str::uuid(), "name" => "Yagba West"]
        ];

        $kwara = [
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Asa"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Baruten"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Edu"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Ekiti"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Ifelodun"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Ilorin East"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Ilorin South"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Ilorin West"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Irepodun"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Isin"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Kaiama"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Moro"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Offa"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Oke Ero"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Oyun"],
            ["state_id" => 25, "slug"=>Str::uuid(), "name" => "Pategi"]
        ];

        $lagos = [
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Agege"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Ajeromi-Ifelodun"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Alimosho"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Amuwo-Odofin"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Apapa"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Badagry"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Epe"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Eti Osa"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Ibeju-Lekki"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Ifako-Ijaiye"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Ikeja"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Ikorodu"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" =>  "Kosofe"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Lagos Island"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Lagos Mainland"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Mushin"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Ojo"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Oshodi-Isolo"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Shomolu"],
            ["state_id" => 26, "slug"=>Str::uuid(), "name" => "Surulere"]
        ];

        $nassarawa = [
            ["state_id" => 27, "slug"=>Str::uuid(), "name" => "Akwanga"],
            ["state_id" => 27, "slug"=>Str::uuid(), "name" => "Awe"],
            ["state_id" => 27, "slug"=>Str::uuid(), "name" => "Doma"],
            ["state_id" => 27, "slug"=>Str::uuid(), "name" => "Karu"],
            ["state_id" => 27, "slug"=>Str::uuid(), "name" => "Keana"],
            ["state_id" => 27, "slug"=>Str::uuid(), "name" => "Keffi"],
            ["state_id" => 27, "slug"=>Str::uuid(), "name" => "Kokona"],
            ["state_id" => 27, "slug"=>Str::uuid(), "name" =>  "Lafia"],
            ["state_id" => 27, "slug"=>Str::uuid(), "name" => "Nasarawa"],
            ["state_id" => 27, "slug"=>Str::uuid(), "name" => "Nasarawa Egon"],
            ["state_id" => 27, "slug"=>Str::uuid(), "name" => "Obi"],
            ["state_id" => 27, "slug"=>Str::uuid(), "name" => "Toto"],
            ["state_id" => 27, "slug"=>Str::uuid(), "name" => "Wamba"]
        ];

        $niger = [
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Agaie"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Agwara"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Bida"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Borgu"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Bosso"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Chanchaga"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Edati"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Gbako"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Gurara"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Katcha"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Kontagora"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Lapai"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Lavun"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Magama"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" =>  "Mariga"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Mashegu"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Mokwa"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Moya"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Paikoro"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Rafi"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Rijau"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Shiroro"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Suleja"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Tafa"],
            ["state_id" => 28, "slug"=>Str::uuid(), "name" => "Wushishi"]
        ];

        $ogun = [
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Abeokuta North"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Abeokuta South"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Ado-Odo Ota"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Egbado North"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Egbado South"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Ewekoro"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Ifo"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" =>  "Ijebu East"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Ijebu North"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Ijebu North East"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Ijebu Ode"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Ikenne"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Imeko Afon"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Ipokia"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Obafemi Owode"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Odeda"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Odogbolu"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Ogun Waterside"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Remo North"],
            ["state_id" => 29, "slug"=>Str::uuid(), "name" => "Shagamu"]
        ];

        $ondo = [
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Akoko North-East"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Akoko North-West"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Akoko South-West"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" =>  "Akoko South-East"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Akure North"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" =>  "Akure South"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Ese Odo"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Idanre"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Ifedore"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" =>  "Ilaje"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Ile Oluji-Okeigbo"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Irele"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Odigbo"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Okitipupa"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Ondo East"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Ondo West"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" =>  "Ose"],
            ["state_id" => 30, "slug"=>Str::uuid(), "name" => "Owo"]
        ];
        $osun = [
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Atakunmosa East"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Atakunmosa West"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Aiyedaade"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Aiyedire"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Boluwaduro"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Boripe"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Ede North"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Ede South"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Ife Central"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Ife East"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" =>  "Ife North"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Ife South"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Egbedore"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Ejigbo"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" =>  "Ifedayo"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Ifelodun"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Ila"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Ilesa East"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Ilesa West"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" =>  "Irepodun"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Irewole"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Isokan"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Iwo"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Obokun"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Odo Otin"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Ola Oluwa"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Olorunda"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Oriade"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Orolu"],
            ["state_id" => 31, "slug"=>Str::uuid(), "name" => "Osogbo"]
        ];
        $oyo = [
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Afijio"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Akinyele"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Atiba"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Atisbo"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" =>  "Egbeda"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Ibadan North"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Ibadan North-East"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Ibadan North-West"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" =>  "Ibadan South-East"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Ibadan South-West"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Ibarapa Central"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Ibarapa East"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Ibarapa North"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Ido"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Irepo"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Iseyin"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" =>  "Itesiwaju"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Iwajowa"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Kajola"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Lagelu"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Ogbomosho North"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Ogbomosho South"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" =>  "Ogo Oluwa"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Olorunsogo"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Oluyole"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" =>  "Ona Ara"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Orelope"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Ori Ire"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" =>  "Oyo"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Oyo East"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Saki East"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Saki West"],
            ["state_id" => 32, "slug"=>Str::uuid(), "name" => "Surulere"]
        ];

        $plateau = [
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Bokkos"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Barkin Ladi"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Bassa"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Jos East"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Jos North"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Jos South"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Kanam"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Kanke"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Langtang South"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Langtang North"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Mangu"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Mikang"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Pankshin"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Qua an Pan"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Riyom"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Shendam"],
            ["state_id" => 33, "slug"=>Str::uuid(), "name" => "Wase"]
        ];

        $sokoto = [
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Binji"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Bodinga"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Dange Shuni"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Gada"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Goronyo"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" =>"Gudu"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Gwadabawa"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Illela"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Isa"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Kebbe"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Kware"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Rabah"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Sabon Birni"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" =>  "Shagari"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Silame"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" =>  "Sokoto North"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Sokoto South"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Tambuwal"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Tangaza"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Tureta"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Wamako"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" =>  "Wurno"],
            ["state_id" => 34, "slug"=>Str::uuid(), "name" => "Yabo"]
        ];

        $taraba = [
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Ardo Kola"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Bali"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Donga"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Gashaka"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Gassol"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Ibi"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Jalingo"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Karim Lamido"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Kumi"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Lau"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Sardauna"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Takum"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Ussa"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Wukari"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Yorro"],
            ["state_id" => 35, "slug"=>Str::uuid(), "name" => "Zing"]
        ];

        $yobe = [
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Bade"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" =>"Bursari"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" =>"Damaturu"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" =>"Fika"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" =>"Fune"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Geidam"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Gujba"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Gulani"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Jakusko"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Karasuwa"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Machina"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Nangere"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Nguru"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Potiskum"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Tarmuwa"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Yunusari"],
            ["state_id" => 36, "slug"=>Str::uuid(), "name" => "Yusufari"]
        ];

        $zamfara = [
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Anka"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Bakura"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" =>"Birnin Magaji Kiyaw"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Bukkuyum"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Bungudu"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Gummi"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Gusau"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Kaura Namoda"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Maradun"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Maru"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Shinkafi"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Talata Mafara"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Chafe"],
            ["state_id" => 37, "slug"=>Str::uuid(), "name" => "Zurmi"]
        ];

        Lga::insert(
            array_merge($yobe, $zamfara, $taraba, $sokoto, $plateau, $oyo, $osun, $ondo, $ogun, $niger, $nassarawa, $lagos, $kwara, $kogi, $kebbi, $katsina, $kano, $kaduna, $jigawa, $imo, $gombe, $abuja, $enugu, $rivers, $ekiti, $edo, $ebonyi, $delta, $crossRiver, $borno, $benue, $bayelsa, $bauchi, $anambra, $akwaIbom, $adamawa, $abia)
        );
    }
}
